# DataSource Config

spring:
  data:
    elasticsearch:
      uris: http://localhost:9200
      connection-timeout: 5s
      socket-timeout: 60s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 18160000
#shiro-redis:
#  enabled: true
#  redis-manager:
#    host: 127.0.0.1:6379