server.port=${random.int(2000,8000)}

rpc.servicePort=20880

rpc.registryType=0

rpc.registryAddress=127.0.0.1:2181

# Elasticsearch（可选，默认 http://localhost:9200）
spring.data.elasticsearch.uris=http://localhost:9200